version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: Europe/Berlin
    allow:
      - dependency-type: production
    open-pull-requests-limit: 20
    versioning-strategy: increase
