version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    assignees:
      - Garfonso

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: Europe/Berlin
    versioning-strategy: increase
    open-pull-requests-limit: 5
    assignees:
      - Garfonso
    ignore:
      # @types/node should always match the minimum major version we support,
      # so only apply patch and minor updates automatically
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directory: "/src"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    assignees:
      - Garfonso
    versioning-strategy: increase
